spring:
  application:
    name: cloud-provider
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8080
dubbo:
  application:
    name: ${spring.application.name}
# 控制注册的纬度是接口级还是实力级，默认是all， 都注册
    register-mode: instance
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: -1
logging:
  level:
    root: info
