server:
  port: 8002
spring:
  application:
    name: cloud-consumer
  cloud:
    nacos:
      server-addr: 172.21.164.164:8848
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: nacos://172.21.164.164:8848
logging:
  level:
    root: info